enhancement: update dependency @grpc-playground/data-registry&proto-r…
atls/apps pull request #25
Opened 2023-09-19 17:20 UTC by shifuwww

…egistry

2023-09-19 17:27 UTC, SlumberyDude approved these changes

2023-09-20 00:06 UTC, TorinAsakura commented
конфликт

2023-09-20 00:08 UTC, TorinAsakura commented
конфликт

2023-09-22 13:44 UTC, SlumberyDude requested changes
Нужно выпилить лишние изменения

2023-09-22 13:44 UTC, SlumberyDude commented on grpc-playground/fragments/sidebar-fragment/package.json
Лишние обновления в таске

2023-09-23 12:30 UTC, SlumberyDude approved these changes

2023-09-25 13:11 UTC, TorinAsakura approved these changes

2023-09-25 13:11 UTC, TorinAsakura commented
конфликты

2023-09-28 17:15 UTC, SlumberyDude commented
@shifuwww Не забывай перезапрашивать ревью

2023-09-28 21:26 UTC, merged