enhancement: update dependency @atls/grpc-playground-app
atls/apps pull request #26
Opened 2023-09-19 17:36 UTC by shifuwww

2023-09-19 19:20 UTC, SlumberyDude requested changes
`@atls/grpc-playground-app` Это воркспейс по адресу `apps/grpc-playground/entrypoints/renderer/package.json` Смотри на поле `name` в `package.json`

А резолющены бафать не надо, я думаю их нужно почистить потому что они оганичивают фактически пакеты внутри зависимостей фиксируя версии

2023-09-20 16:37 UTC, SlumberyDude requested changes
@shifuwww У тебя названия коммитов неправильные. Если это фича, то начинаться должны с `feat:` Доступные ключевые слова бери в конвенции по коммитам. enhancement это лейбл таски, они не являются ключевыми словами.

2023-09-20 16:37 UTC, SlumberyDude commented on grpc-playground/fragments/sidebar-fragment/package.json
Этот файл не относится к таске, это другой пакет

2023-09-20 16:37 UTC, SlumberyDude commented on grpc-playground/fragments/tabs-fragment/package.json
Этот тоже из другого таска. Ты фиксил версии из-за того, что чеки поехали после того, как убрал resolutions? Тогда можно по мере обновления в resolutions ставить заплатки конкретно на модули где ломаются зависимости.

2023-09-20 16:44 UTC, SlumberyDude commented
@shifuwww На будущее используй пожалуйста для коммитов след. ключевые слова:

`feat` - для фичи
`fix` - фикс бага
`chore` - не баг и не фича
`test` - пишешь тест

По поводу точечных резолюшенов которыми можно сделать заплатку на конкретные пакеты из корневого https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

То есть, если хотим убрать общую заплатку на `@emotion/react` и оставить ее для пакета `@grpc-playground/tabs-fragment` То в резолюшенах должно сработать что-то вроде 
```
"resolutions": {
    "@grpc-playground/tabs-fragment/@emotion/react": "11.9.3",
    ...
```

2023-09-20 16:46 UTC, shifuwww commented on grpc-playground/fragments/sidebar-fragment/package.json
Я делал rebase master ветки, кажется не надо было да?

2023-09-20 16:47 UTC, SlumberyDude commented on grpc-playground/fragments/sidebar-fragment/package.json
@shifuwww Да вроде надо было, чтобы от конфликтов избавиться, но не припомню чтобы после этого индексировались такие изменения

2023-09-20 16:50 UTC, shifuwww commented on grpc-playground/fragments/sidebar-fragment/package.json
> Да вроде надо было, чтобы от конфликтов избавиться, но не припомню чтобы после этого индексировались такие изменения
>
Просто эти ветки замерджены, я не перетеру их если буду убирать их здесь?

2023-09-20 16:51 UTC, shifuwww commented on grpc-playground/fragments/sidebar-fragment/package.json
Надо было делать наоборот?

2023-09-20 16:54 UTC, SlumberyDude commented on grpc-playground/fragments/sidebar-fragment/package.json
@shifuwww Мы делаем только ребейзы.

1. Обновляем ветки мастер и фичу на локалке.
2. Делаем ребейз фичи на мастер
3. Делаем пулл удаленной фичи на локальную со стратегией ребейз
4. Пушим

2023-09-20 17:06 UTC, SlumberyDude commented
@shifuwww У тебя почему-то здесь даже первый коммит это изменения другого пакета. Мерж мастера здесь не причем, но в след. разы все равно делай ребейз. 

Надо как-то выпиливать коммиты, которые меняли не те файлы

2023-09-22 10:41 UTC, SlumberyDude commented
@shifuwww Называй коммиты правильно пожалуйста

2023-09-22 10:41 UTC, SlumberyDude commented
Или это ребейз старых?
Тогда ок

2023-09-22 10:42 UTC, shifuwww commented
> Или это ребейз старых?
Тогда ок
>
Ребейз старых

2023-09-22 10:43 UTC, shifuwww commented
@SlumberyDude 
>@shifuwww Мы делаем только ребейзы.

1. Обновляем ветки мастер и фичу на локалке.

2. Делаем ребейз фичи на мастер
3. Делаем пулл удаленной фичи на локальную со стратегией ребейз
4. Пушим
>
Я кажется где то не так сделал, конфликты не ушли

2023-09-22 10:45 UTC, SlumberyDude commented
@shifuwww 

Да, наверное что-то не так

2023-09-22 10:51 UTC, shifuwww commented
> @shifuwww Мы делаем только ребейзы.
 >
Вроде бы вот так?
1. `git checkout master & git pull master` и `git checkout <nameOfBranch> &git pull <nameOfBranch>`
 2. `git checkout master` и после `git rebase <nameOfBranch>`
 3. `git checkout <nameOfBranch>` и 'git pull`
 4. 'git push'

2023-09-22 10:59 UTC, SlumberyDude commented
@shifuwww 

> 2. git checkout master и после git rebase <nameOfBranch>

Не, нужно находясь на фиче делать ребейз на мастер. `git checkout <nameOfBranch>` -> `git rebase master`

> 3 git checkout <nameOfBranch> и git pull

Делай `git pull --rebase` или выставь в настройках гита стратегию ребейз по умолчанию. Вобщем пулл тоже должен быть ребейзом

2023-09-22 12:42 UTC, SlumberyDude commented
@shifuwww Не выходит конфликты пофиксить да? У меня тоже не выходит, но на другом проекте)

2023-09-22 12:43 UTC, shifuwww commented
> @shifuwww Не выходит конфликты пофиксить да? У меня тоже не выходит, но на другом проекте)
>
Даааааааа( эх)

2023-09-22 13:38 UTC, SlumberyDude requested changes

2023-09-22 13:38 UTC, SlumberyDude commented on grpc-playground/entrypoints/renderer/package.json
> +    "@types/express": "^4.17.17",
зафиксируй версию

2023-09-22 16:25 UTC, SlumberyDude requested changes

2023-09-22 16:25 UTC, SlumberyDude commented on grpc-playground/pages/index-page/package.json
Лишний пакет в обнове, он уже был обновлен 1 PR назад

2023-09-22 16:38 UTC, closed without merging